// Code generated by protoc-gen-go. DO NOT EDIT.
// source: testdata/testdata.proto

package testdata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Input struct {
	S                    string   `protobuf:"bytes,1,opt,name=s,proto3" json:"s,omitempty"`
	D                    float64  `protobuf:"fixed64,2,opt,name=d,proto3" json:"d,omitempty"`
	I                    int32    `protobuf:"varint,4,opt,name=i,proto3" json:"i,omitempty"`
	B                    bool     `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_06effb99b55a0a0d, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Input) GetD() float64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *Input) GetI() int32 {
	if m != nil {
		return m.I
	}
	return 0
}

func (m *Input) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

type Output struct {
	S                    string   `protobuf:"bytes,5,opt,name=s,proto3" json:"s,omitempty"`
	D                    float64  `protobuf:"fixed64,6,opt,name=d,proto3" json:"d,omitempty"`
	I                    int32    `protobuf:"varint,7,opt,name=i,proto3" json:"i,omitempty"`
	B                    bool     `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_06effb99b55a0a0d, []int{1}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

func (m *Output) GetD() float64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *Output) GetI() int32 {
	if m != nil {
		return m.I
	}
	return 0
}

func (m *Output) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

func init() {
	proto.RegisterType((*Input)(nil), "testdata.Input")
	proto.RegisterType((*Output)(nil), "testdata.Output")
}

func init() { proto.RegisterFile("testdata/testdata.proto", fileDescriptor_06effb99b55a0a0d) }

var fileDescriptor_06effb99b55a0a0d = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x49, 0x2d, 0x2e,
	0x49, 0x49, 0x2c, 0x49, 0xd4, 0x87, 0x31, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0x60,
	0x7c, 0x25, 0x7b, 0x2e, 0x56, 0xcf, 0xbc, 0x82, 0xd2, 0x12, 0x21, 0x1e, 0x2e, 0xc6, 0x62, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xc6, 0x62, 0x10, 0x2f, 0x45, 0x82, 0x49, 0x81, 0x51, 0x83,
	0x31, 0x88, 0x31, 0x05, 0xc4, 0xcb, 0x94, 0x60, 0x51, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xcc, 0x04,
	0xf1, 0x92, 0x24, 0x98, 0x15, 0x18, 0x35, 0x38, 0x82, 0x18, 0x93, 0x94, 0x1c, 0xb8, 0xd8, 0xfc,
	0x4b, 0x4b, 0xe0, 0x26, 0xb0, 0xa2, 0x98, 0xc0, 0x86, 0x62, 0x02, 0x3b, 0x8a, 0x09, 0x8c, 0x50,
	0x13, 0x92, 0xd8, 0xc0, 0x6e, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xeb, 0xe6, 0x4d,
	0xae, 0x00, 0x00, 0x00,
}
